# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haider Malik Protfolio
email: haidermalik504@gmailcom
description: > # this means to ignore newlines until "baseurl:"
  Mean Stack Developer, Angular Js , Angular 2, Sails js, Express Js, Node js,Mongo 
  Mysql React, Ionic, React Native, Ionic2
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haiderportolio.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  HaiderMalik12
google_username:  haidermalik504@gmail.com

permalink: /:categories/title
links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me 
    url: /hire-me

# Build settings
markdown: kramdown
